version: "3"

services:
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust      
    ports:
      - "5432:5432"
    #volumes:
      #- ${DATA_DB}:/var/lib/postgresql/data
  app:
    # build: .
    image: sappachok/docker-datasci:latest
    container_name: django-gunicorn
    restart: always
    env_file:
      - .env
    volumes:
      - ${DATA_APP_ROOT}:/src
      #- /d/repo/django-datasci-app:/src
    ports:
      - "8000:8000"
      - "5678:5678"
      - "8070:8070"
    command:
      "gunicorn --workers=5 --timeout=0 --bind=0.0.0.0:8000 mysite.wsgi:application"
    depends_on:
      - db
  nginx:
    image: nginx:1.17
    container_name: ngx
    ports:
      - "9999:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app
