version: "3"

services:
  db:
    image: postgres
    container_name: db
    ports:
      - "5432:5432"
  app:
    build: .
    container_name: django-gunicorn
    restart: always
    env_file:
      - django.env
    volumes:
      - ./app:/src
    ports:
      - "8000:8000"
    command:
      "gunicorn --workers=5 --timeout=0 --bind=0.0.0.0:8000 mysite.wsgi:application"
    depends_on:
      - db
  nginx:
    image: nginx:1.17
    container_name: ngx
    ports:
      - "9999:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app
