# Generated by Django 2.2.4 on 2019-08-09 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0002_pythoncode'),
    ]

    operations = [
        migrations.CreateModel(
            name='PythonLabs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=500)),
                ('script', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='pythoncode',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
