# Generated by Django 2.2.4 on 2019-08-09 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0003_auto_20190809_1724'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PythonLabs',
            new_name='PythonLab',
        ),
    ]
