# Generated by Django 2.2.4 on 2019-08-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0004_auto_20190809_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='pythonlab',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
