# Generated by Django 2.2.4 on 2019-08-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0005_pythonlab_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('parentid', models.CharField(choices=[('ASIAN', 'Asian'), ('BLACK', 'Black'), ('LATINO', 'Latino'), ('WHITE', 'White'), ('OTHER', 'Other'), ('?', 'Unknown')], default='?', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='pythonlab',
            name='categories',
            field=models.CharField(choices=[('ASIAN', 'Asian'), ('BLACK', 'Black'), ('LATINO', 'Latino'), ('WHITE', 'White'), ('OTHER', 'Other'), ('?', 'Unknown')], default='', max_length=10),
        ),
    ]
