# Generated by Django 2.2.4 on 2019-08-10 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0006_auto_20190810_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pythonlab',
            name='categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='editor.LabCategory'),
        ),
    ]
