# Generated by Django 2.2.4 on 2019-08-10 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0009_auto_20190810_1557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labcategory',
            old_name='parentid',
            new_name='parent',
        ),
    ]
